# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from arlie.envs.lunar_lander.python_protos import Lunar_pb2 as Lunar__pb2


class LunarServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetActionDim = channel.unary_unary(
        '/LunarService/GetActionDim',
        request_serializer=Lunar__pb2.ServiceMessage.SerializeToString,
        response_deserializer=Lunar__pb2.DimResult.FromString,
        )
    self.GetObservationDim = channel.unary_unary(
        '/LunarService/GetObservationDim',
        request_serializer=Lunar__pb2.ServiceMessage.SerializeToString,
        response_deserializer=Lunar__pb2.DimResult.FromString,
        )
    self.PerformAction = channel.unary_unary(
        '/LunarService/PerformAction',
        request_serializer=Lunar__pb2.Action.SerializeToString,
        response_deserializer=Lunar__pb2.ActionResult.FromString,
        )
    self.Render = channel.unary_unary(
        '/LunarService/Render',
        request_serializer=Lunar__pb2.ServiceMessage.SerializeToString,
        response_deserializer=Lunar__pb2.ServiceMessage.FromString,
        )
    self.Reset = channel.unary_unary(
        '/LunarService/Reset',
        request_serializer=Lunar__pb2.ServiceMessage.SerializeToString,
        response_deserializer=Lunar__pb2.Observation.FromString,
        )


class LunarServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetActionDim(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetObservationDim(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PerformAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Render(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LunarServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetActionDim': grpc.unary_unary_rpc_method_handler(
          servicer.GetActionDim,
          request_deserializer=Lunar__pb2.ServiceMessage.FromString,
          response_serializer=Lunar__pb2.DimResult.SerializeToString,
      ),
      'GetObservationDim': grpc.unary_unary_rpc_method_handler(
          servicer.GetObservationDim,
          request_deserializer=Lunar__pb2.ServiceMessage.FromString,
          response_serializer=Lunar__pb2.DimResult.SerializeToString,
      ),
      'PerformAction': grpc.unary_unary_rpc_method_handler(
          servicer.PerformAction,
          request_deserializer=Lunar__pb2.Action.FromString,
          response_serializer=Lunar__pb2.ActionResult.SerializeToString,
      ),
      'Render': grpc.unary_unary_rpc_method_handler(
          servicer.Render,
          request_deserializer=Lunar__pb2.ServiceMessage.FromString,
          response_serializer=Lunar__pb2.ServiceMessage.SerializeToString,
      ),
      'Reset': grpc.unary_unary_rpc_method_handler(
          servicer.Reset,
          request_deserializer=Lunar__pb2.ServiceMessage.FromString,
          response_serializer=Lunar__pb2.Observation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'LunarService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
